### ISSUE TITLE
JsonMessage cannot deserialize ParameterRsp containing ConfigParam

### ISSUE THREAD

**Issue by ngyewch** [org-arl/fjage-sentuator#9]
This probably has to do with `JsonMessage` expecting an enum.

Sample test project:
* https://github.com/ngyewch/fjage-sentuator-configparam-test

Sample code:
```
    final ParameterReq parameterReq = new ParameterReq();
    final ParameterRsp parameterRsp = new ParameterRsp(parameterReq);
    parameterRsp.set(SentuatorParam.enable, true, false);
    parameterRsp.set(new ConfigParam("level"), 1, false);

    final JsonMessage jsonMessage = new JsonMessage();
    jsonMessage.message = parameterRsp;
    final String json = jsonMessage.toJson();
    log.info(">> " + json);

    final JsonMessage jsonMessage1 = JsonMessage.fromJson(json);
    log.info("<< " + jsonMessage1.toJson());
```

Exception thrown:
```
    java.lang.IllegalArgumentException: org.arl.fjage.sentuator.ConfigParam is not an enum type
        at java.base/java.lang.Class.enumConstantDirectory(Class.java:3578)
        at java.base/java.lang.Enum.valueOf(Enum.java:234)
        at org.arl.fjage.remote.EnumTypeAdapter.read(EnumTypeAdapter.java:88)
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at org.arl.fjage.remote.MessageAdapterFactory$1.read(MessageAdapterFactory.java:150)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at org.arl.fjage.remote.JsonMessage.fromJson(JsonMessage.java:59)
        at JsonTests.serializeAndDeserialize(JsonTests.java:52)
        at JsonTests.testParameterRspWithCustomConfig(JsonTests.java:30)
```

**Comment by mchitre** [comment]
Hmm.

`Parameter` is expected to be an enum, and so we try to get the enum for it while deserializing. We have a special case for `NamedParameter`, which is the only non-enum parameter (other than `ConfigParam` now). Either we can convert `ConfigParam` to extend `Enum` or `NamedParameter`, or we may need special handling. Let me explore both and see what works.

**Comment by ngyewch** [comment]
Yeah `NamedParameter` would make sense (already in fjage, maybe some impact to fjage-sentuator) . 

Alternatively, if a class implements `Parameter` but is not an enum, instantiate using `<constructor>(String name)`. (needs changes to fjage).

First option probably better.

**Comment by mchitre** [comment]
Fixed and tested. Waiting for PR review.

**Comment by ngyewch** [comment]
Looks good!
